### PR TITLE
Setting JP og:Image

### LINKED ISSUE #36: Setting: Twitter OGP
I want to create a Twitter card (OGP) because it doesn't show up when I publish on Twitter.

[Image from Gyazo](https://gyazo.com/ccfb5a324e77c6739fdec85f46e25ae1)

### PR DESCRIPTION
**Pull request by yamanoku**
resolve #36

### CODE REVIEW

**Review by ktquez — APPROVED** [review]

**Comment by yamanoku** [comment]
👍 
Screen Shot 2021-01-24 at 8 29 24

Twitter cards with jp URLs don't reflect the images yet.
I'm sure it'll be able to see this once it's applied to master merged. @ktquez 
Screen Shot 2021-01-24 at 8 30 28

**Comment by ktquez** [comment]
Vuepress managed to replace `twitter:image`, but the` og:image` it doubled.

image

See if modifying the `og:image` to
```js
['meta', {property: 'og:image', content: 'https://vue-a11y.com/img/social-share.png'}]
```
We can avoid this duplicate.

**Comment by yamanoku** [comment]
@ktquez I found out why there was a duplication.

It was because I was trying to overwrite the meta `name` where it was set in the meta `property`.
I was able to avoid this duplication with [`4964ce1` (#43)](https://github.com/vue-a11y/vue-a11y.com/pull/43/commits/4964ce1f6e1c9a848772a5ed7ab9555150380df8).

Screen Shot 2021-01-24 at 12 17 29

**Comment by ktquez** [comment]
Awesome!!!
Thanks @yamanoku

**Comment by yamanoku** [comment]
🎉 

jp
Screen Shot 2021-01-24 at 12 45 53

en
Screen Shot 2021-01-24 at 12 45 44

**Pull request merged**
